### ISSUE TITLE
Updating ADS Token does nothing.

### ISSUE THREAD

**Issue by EricDepagne** [onekiloparsec/arcsecond-public#13]
I tried to update my ADS token, by entering it where asked and then pressing Update.
The button changes to "Updating", and it stays like this.
I tried with Firefox (59), Chromium (65).

**Comment by onekiloparsec** [comment]
Damn.

**Comment by onekiloparsec** [comment]
Fixed.

**Comment by EricDepagne** [comment]
It works now, thanks!
