### ISSUE TITLE
Querying M56 and M102 returns no coordinates

### ISSUE THREAD

**Issue by PawelPleskaczynski** [onekiloparsec/arcsecond-public#22]
Querying M56 or M102 (and probably some other objects) returns no everything but coordinates. Here's what API returns for "M56" query:

`
{"name":"M56","ICRS_coordinates":null,"ecliptic_coordinates":null,"galactic_coordinates":null,"spectral_type":null,"morphological_type":null,"proper_motion":null,"parallax":null,"radial_velocity":null,"age":null,"mass":null,"radius":null,"distance":null,"metallicity":null,"effective_temperature":null,"aliases":[{"name":"[KPS2012] MWSC 3077","catalogue_url":"http://vizier.u-strasbg.fr/viz-bin/VizieR-S?%5BKPS2012%5D%20MWSC%203077"},{"name":"NGC 6779","catalogue_url":"http://vizier.u-strasbg.fr/viz-bin/VizieR-S?NGC%20%206779"},{"name":"GCRV 11736","catalogue_url":"http://vizier.u-strasbg.fr/viz-bin/VizieR-S?GCRV%2011736"},{"name":"GCl 110","catalogue_url":"http://vizier.u-strasbg.fr/viz-bin/VizieR-S?GCl%20110"},{"name":"CSI+30-19146 3","catalogue_url":"http://vizier.u-strasbg.fr/viz-bin/VizieR-S?CSI%2B30-19146%20%203"},{"name":"C 1914+300","catalogue_url":"http://vizier.u-strasbg.fr/viz-bin/VizieR-S?C%201914%2B300"},{"name":"M 56","catalogue_url":"http://vizier.u-strasbg.fr/viz-bin/VizieR-S?M%20%2056"}],"object_types":["*","Cl*","GlC"],"fluxes":[{"name":"z","value":7.748,"error":0.044,"error_max":null,"error_min":null,"bibcode":"2014MNRAS.437.1725V","quality":"C","system":"AB","unit":"mag","flags":""},{"name":"i","value":7.879,"error":0.044,"error_max":null,"error_min":null,"bibcode":"2014MNRAS.437.1725V","quality":"C","system":"AB","unit":"mag","flags":""},{"name":"r","value":8.138,"error":0.044,"error_max":null,"error_min":null,"bibcode":"2014MNRAS.437.1725V","quality":"C","system":"AB","unit":"mag","flags":""},{"name":"g","value":8.613,"error":0.03,"error_max":null,"error_min":null,"bibcode":"2014MNRAS.437.1725V","quality":"C","system":"AB","unit":"mag","flags":""},{"name":"K","value":5.58,"error":null,"error_max":null,"error_min":null,"bibcode":"2008MNRAS.389.1924F","quality":"D","system":"Vega","unit":"mag","flags":""},{"name":"B","value":8.9,"error":null,"error_max":null,"error_min":null,"bibcode":"","quality":"D","system":"Vega","unit":"mag","flags":""}],"planets":[],"astronomer_telegrams":[]}
`

**Comment by PawelPleskaczynski** [comment]
M76 is not working as well

**Comment by PawelPleskaczynski** [comment]
But M 76 is working

**Comment by onekiloparsec** [comment]
Investigating. Thanks for the bug report.

**Comment by onekiloparsec** [comment]
I just deployed a fix. I am not entirely satisfied as I couldn't find an explanation as why some objects were in that state. But I made sure that if we don't get coordinates, we'll always query SIMBAD. The problem here was to avoid querying SIMBAD all the time when it is not necessary (to speed up responses). Hence there is a 1 week filter. Let see how it goes.
